# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main", "dev", "yhj" ]
  pull_request:
    branches: [ "main", "dev" ]

permissions:
  contents: read

jobs:
  # spring boot 빌드 & 도커 허브 푸시
  build-docker-image:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      # spring boot 애플리케이션 빌드
      - name: Build with Gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25
        with:
          arguments: clean bootJar
      # 도커 이미지 빌드
      - name: docker image build
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/travelog-board .

      # 도커 허브 로그인
      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: docker hub push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/travelog-board

      # vm 접속
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_SSH_ID }}
          password: ${{ secrets.REMOTE_SSH_PASSWORD }}
          script: |
            docker ps -a
            docker stop travelog-board
            docker rm travelog-board
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/travelog-board
            docker run --name travelog-board -d -p 8082:8082 travelog-board